export { default as Dialog } from './Dialog.vue';
export { default as DialogRoot } from './Dialog.vue';
export { default as DialogTrigger } from './DialogTrigger.vue';
export { default as DialogPortal } from './DialogPortal.vue';
export { default as DialogOverlay } from './DialogOverlay.vue';
export { dialogOverlayVariants } from './DialogOverlay.vue';
export { default as DialogContent } from './DialogContent.vue';
export { dialogContentVariants } from './DialogContent.vue';
export { default as DialogClose } from './DialogClose.vue';
export { default as DialogTitle } from './DialogTitle.vue';
export { default as DialogDescription } from './DialogDescription.vue';
