package db

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"io/fs"
	"os"
	"sort"
	"strings"

	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/jackc/pgx/v5/stdlib"
	"github.com/pressly/goose/v3"
)

// ExtraMigrationsTableName 外部专有迁移的版本表名，与核心迁移版本隔离
const ExtraMigrationsTableName = "goose_db_version_extra"

// Migrate 使用成熟的数据库迁移库 github.com/pressly/goose/v3 执行 SQL 迁移。
// 保持对外签名完全不变，且自动兼容历史 schema_migrations 记录。
func Migrate(ctx context.Context, pool *pgxpool.Pool, dir string) error {
	return MigrateWithExtra(ctx, pool, dir, nil)
}

// MigrateExtra 执行外部专有迁移，使用独立的 goose_db_version_extra 表记录版本。
func MigrateExtra(ctx context.Context, pool *pgxpool.Pool, extraFS fs.FS) error {
	return MigrateWithExtra(ctx, pool, "", extraFS)
}

// MigrateWithExtra 统一在分布式锁下执行基座核心迁移与外部专有迁移（双轨迁移流水线）。
func MigrateWithExtra(ctx context.Context, pool *pgxpool.Pool, dir string, extraFS fs.FS) error {
	db := stdlib.OpenDBFromPool(pool)
	defer func() { _ = db.Close() }()

	return MigrateDBWithExtra(ctx, db, dir, extraFS)
}

// MigrateDBWithExtra 在已有 *sql.DB 实例上执行双轨迁移（先核心迁移，后外部迁移）
func MigrateDBWithExtra(ctx context.Context, db *sql.DB, dir string, extraFS fs.FS) error {
	if err := goose.SetDialect("postgres"); err != nil {
		return fmt.Errorf("goose set dialect: %w", err)
	}

	// 并发多副本同时启动时,两个进程可能同时执行 DDL 与 goose_db_version 写入。
	// 用 advisory lock 串行化迁移;锁挂在一条专用连接上(会话级锁),
	// 迁移期间这条连接不释放,其它副本在这里阻塞等到锁释放后再跑幂等迁移。
	lockConn, err := db.Conn(ctx)
	if err != nil {
		return fmt.Errorf("acquire migration connection: %w", err)
	}
	defer func() { _ = lockConn.Close() }()
	if _, err := lockConn.ExecContext(ctx, `SELECT pg_advisory_lock(hashtext('janus-migrate'))`); err != nil {
		return fmt.Errorf("acquire migration lock: %w", err)
	}
	defer func() {
		_, _ = lockConn.ExecContext(context.WithoutCancel(ctx), `SELECT pg_advisory_unlock(hashtext('janus-migrate'))`)
	}()

	// 第一轨：基座核心迁移
	if dir != "" {
		if err := syncLegacyMigrations(ctx, db, dir); err != nil {
			return fmt.Errorf("sync legacy migrations: %w", err)
		}
		if err := goose.UpContext(ctx, db, dir); err != nil {
			return fmt.Errorf("goose up: %w", err)
		}
	}

	// 第二轨：外部专有迁移
	if extraFS != nil {
		origTable := goose.TableName()
		goose.SetTableName(ExtraMigrationsTableName)
		goose.SetBaseFS(extraFS)
		err := goose.UpContext(ctx, db, ".")
		goose.SetBaseFS(nil)
		goose.SetTableName(origTable)
		if err != nil && !errors.Is(err, goose.ErrNoMigrations) && !errors.Is(err, goose.ErrNoMigrationFiles) {
			return fmt.Errorf("goose extra up: %w", err)
		}
	}

	return nil
}

// syncLegacyMigrations 检测是否存在旧版 schema_migrations，并将已应用版本同步到 goose_db_version。
func syncLegacyMigrations(ctx context.Context, db *sql.DB, dir string) error {
	var exists bool
	queryTable := `SELECT EXISTS (
		SELECT FROM information_schema.tables 
		WHERE table_schema = 'public' AND table_name = 'schema_migrations'
	)`
	if err := db.QueryRowContext(ctx, queryTable).Scan(&exists); err != nil {
		return fmt.Errorf("check legacy schema_migrations: %w", err)
	} else if !exists {
		return nil
	}

	// 确保 goose_db_version 表存在
	_, err := db.ExecContext(ctx, `
		CREATE TABLE IF NOT EXISTS goose_db_version (
			id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			version_id bigint NOT NULL,
			is_applied boolean NOT NULL,
			tstamp timestamp NOT NULL DEFAULT now()
		)
	`)
	if err != nil {
		return fmt.Errorf("ensure goose_db_version: %w", err)
	}

	entries, err := os.ReadDir(dir)
	if err != nil {
		return fmt.Errorf("read migrations dir: %w", err)
	}
	var sqlFiles []string
	for _, e := range entries {
		if !e.IsDir() && strings.HasSuffix(e.Name(), ".sql") {
			sqlFiles = append(sqlFiles, e.Name())
		}
	}
	sort.Strings(sqlFiles)

	for _, filename := range sqlFiles {
		var applied bool
		err := db.QueryRowContext(ctx, `SELECT EXISTS(SELECT 1 FROM schema_migrations WHERE version = $1)`, filename).Scan(&applied)
		if err != nil {
			return fmt.Errorf("check legacy version %s: %w", filename, err)
		}
		if !applied {
			continue
		}

		v, parseErr := goose.NumericComponent(filename)
		if parseErr != nil {
			continue
		}

		// 检查 goose_db_version 中是否已经记录
		var recorded bool
		if err := db.QueryRowContext(ctx, `SELECT EXISTS(SELECT 1 FROM goose_db_version WHERE version_id = $1)`, v).Scan(&recorded); err != nil {
			return fmt.Errorf("check goose version %d: %w", v, err)
		}
		if !recorded {
			if _, err := db.ExecContext(ctx, `
				INSERT INTO goose_db_version (version_id, is_applied, tstamp)
				VALUES ($1, true, now())
			`, v); err != nil {
				return fmt.Errorf("record legacy version %d: %w", v, err)
			}
		}
	}

	return nil
}
