package db

import (
	"context"
	"database/sql"
	"fmt"
	"os"
	"sort"
	"strings"

	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/jackc/pgx/v5/stdlib"
	"github.com/pressly/goose/v3"
)

// Migrate 使用成熟的数据库迁移库 github.com/pressly/goose/v3 执行 SQL 迁移。
// 保持对外签名完全不变，且自动兼容历史 schema_migrations 记录。
func Migrate(ctx context.Context, pool *pgxpool.Pool, dir string) error {
	db := stdlib.OpenDBFromPool(pool)
	defer func() { _ = db.Close() }()

	if err := goose.SetDialect("postgres"); err != nil {
		return fmt.Errorf("goose set dialect: %w", err)
	}

	// 并发多副本同时启动时,两个进程可能同时执行 DDL 与 goose_db_version 写入。
	// 用 advisory lock 串行化迁移;锁挂在一条专用连接上(会话级锁),
	// 迁移期间这条连接不释放,其它副本在这里阻塞等到锁释放后再跑幂等迁移。
	lockConn, err := db.Conn(ctx)
	if err != nil {
		return fmt.Errorf("acquire migration connection: %w", err)
	}
	defer func() { _ = lockConn.Close() }()
	if _, err := lockConn.ExecContext(ctx, `SELECT pg_advisory_lock(hashtext('janus-migrate'))`); err != nil {
		return fmt.Errorf("acquire migration lock: %w", err)
	}
	defer func() {
		_, _ = lockConn.ExecContext(context.WithoutCancel(ctx), `SELECT pg_advisory_unlock(hashtext('janus-migrate'))`)
	}()

	// 平滑兼容历史迁移记录：
	// Janus 早期使用自研 schema_migrations 表（存储 0001_init.sql 等文件名）。
	// goose 默认使用 goose_db_version 表（版本号为 int64，如 1, 2, 3）。
	// 为防止切换到 goose 时重复执行已有历史迁移导致冲突，在此做一次平滑对齐。
	if err := syncLegacyMigrations(ctx, db, dir); err != nil {
		return fmt.Errorf("sync legacy migrations: %w", err)
	}

	// 使用 goose 执行迁移
	if err := goose.UpContext(ctx, db, dir); err != nil {
		return fmt.Errorf("goose up: %w", err)
	}

	return nil
}

// syncLegacyMigrations 检测是否存在旧版 schema_migrations，并将已应用版本同步到 goose_db_version。
func syncLegacyMigrations(ctx context.Context, db *sql.DB, dir string) error {
	var exists bool
	queryTable := `SELECT EXISTS (
		SELECT FROM information_schema.tables 
		WHERE table_schema = 'public' AND table_name = 'schema_migrations'
	)`
	if err := db.QueryRowContext(ctx, queryTable).Scan(&exists); err != nil {
		return fmt.Errorf("check legacy schema_migrations: %w", err)
	} else if !exists {
		return nil
	}

	// 确保 goose_db_version 表存在
	_, err := db.ExecContext(ctx, `
		CREATE TABLE IF NOT EXISTS goose_db_version (
			id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			version_id bigint NOT NULL,
			is_applied boolean NOT NULL,
			tstamp timestamp NOT NULL DEFAULT now()
		)
	`)
	if err != nil {
		return fmt.Errorf("ensure goose_db_version: %w", err)
	}

	entries, err := os.ReadDir(dir)
	if err != nil {
		return fmt.Errorf("read migrations dir: %w", err)
	}
	var sqlFiles []string
	for _, e := range entries {
		if !e.IsDir() && strings.HasSuffix(e.Name(), ".sql") {
			sqlFiles = append(sqlFiles, e.Name())
		}
	}
	sort.Strings(sqlFiles)

	for _, filename := range sqlFiles {
		var applied bool
		err := db.QueryRowContext(ctx, `SELECT EXISTS(SELECT 1 FROM schema_migrations WHERE version = $1)`, filename).Scan(&applied)
		if err != nil {
			return fmt.Errorf("check legacy version %s: %w", filename, err)
		}
		if !applied {
			continue
		}

		v, parseErr := goose.NumericComponent(filename)
		if parseErr != nil {
			continue
		}

		// 检查 goose_db_version 中是否已经记录
		var recorded bool
		if err := db.QueryRowContext(ctx, `SELECT EXISTS(SELECT 1 FROM goose_db_version WHERE version_id = $1)`, v).Scan(&recorded); err != nil {
			return fmt.Errorf("check goose version %d: %w", v, err)
		}
		if !recorded {
			if _, err := db.ExecContext(ctx, `
				INSERT INTO goose_db_version (version_id, is_applied, tstamp)
				VALUES ($1, true, now())
			`, v); err != nil {
				return fmt.Errorf("record legacy version %d: %w", v, err)
			}
		}
	}

	return nil
}
